version: '3.8'

services:
  # Core services (always enabled)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-3000}:3000"
    environment:
      - VITE_API_URL=http://api:8080
    depends_on:
      - api

  api:
    image: elizaos/eliza:latest
    ports:
      - "8080:8080"
    volumes:
      - ./characters:/app/characters
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production

  # Optional services (commented by default)
  # Uncomment and configure as needed
  
  # discord:
  #   image: elizaos/eliza-discord:latest
  #   env_file: .env
  #   depends_on:
  #     - api

  # telegram:
  #   image: elizaos/eliza-telegram:latest
  #   env_file: .env
  #   depends_on:
  #     - api

  # twitter:
  #   image: elizaos/eliza-twitter:latest
  #   env_file: .env
  #   depends_on:
  #     - api 